[package]
name = "befunge"
version = "0.1.0"
authors = ["Sam Sleight <samuel@sleig.ht>"]
edition = "2018"

[dependencies]
structopt = "0.2.15"
pipeline = { path = "pipeline" }
llvm-wrapper = { path = "llvm-wrapper" }

[workspace]
